# Generated by Django 3.2.9 on 2021-11-14 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('timedate', models.DateTimeField()),
                ('text', models.TextField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='reviews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.reviews'),
        ),
    ]
