# Generated by Django 3.2.9 on 2021-11-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20211115_0350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.RemoveField(
            model_name='articles',
            name='reviews',
        ),
        migrations.AddField(
            model_name='articles',
            name='reviews',
            field=models.ManyToManyField(to='news.Reviews'),
        ),
    ]
