# Generated by Django 3.2.9 on 2021-11-15 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20211115_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='reviews',
        ),
        migrations.AddField(
            model_name='reviews',
            name='articles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.articles'),
        ),
    ]
